### ISSUE TITLE
[08:26:30] [Server thread/ERROR]: Error occurred while enabling AutoServerUpdater v1.0.2 (Is it up to date?)

### ISSUE THREAD

**Issue by OutHimic** [notTamion/AutoServerUpdater#20]
[08:26:26] [Server thread/INFO]: [AutoServerUpdater] Enabling AutoServerUpdater v1.0.2
[08:26:30] [Server thread/WARN]: [AutoServerUpdater] Old Paper build detected. Updating from build 107 to 108
[08:26:30] [Server thread/ERROR]: Error occurred while enabling AutoServerUpdater v1.0.2 (Is it up to date?)
java.lang.RuntimeException: java.nio.file.FileSystemException: paper-1.21-107.jar: 另一个程序正在使用此文件，进程无法访问。
	at AutoServerUpdater-1.0.2.jar/de.tamion.AutoServerUpdater.onEnable(AutoServerUpdater.java:51) ~[AutoServerUpdater-1.0.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-107-aa36ae6]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-107-aa36ae6]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-107-aa36ae6]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-107-aa36ae6]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:293) ~[paper-1.21.jar:1.21-107-aa36ae6]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-107-aa36ae6]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-107-aa36ae6]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.nio.file.FileSystemException: paper-1.21-107.jar: 另一个程序正在使用此文件，进程无法访问。
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92) ~[?:?]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:273) ~[?:?]
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:109) ~[?:?]
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191) ~[?:?]
	at java.base/java.nio.file.Files.copy(Files.java:3133) ~[?:?]
	at org.apache.commons.io.file.PathUtils.copy(PathUtils.java:277) ~[commons-io-2.15.1.jar:2.15.1]
	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1053) ~[commons-io-2.15.1.jar:2.15.1]
	at AutoServerUpdater-1.0.2.jar/de.tamion.AutoServerUpdater.onEnable(AutoServerUpdater.java:31) ~[AutoServerUpdater-1.0.2.jar:?]
	... 10 more
[08:26:30] [Server thread/INFO]: [AutoServerUpdater] Disabling AutoServerUpdater v1.0.2

**Comment by notTamion** [comment]
I will take a closer look later today however  i assume that this is because some java 21 distros dont allow modifying loaded jar files.

**Comment by OutHimic** [comment]
> I will take a closer look later today however i assume that this is because some java 21 distros dont allow modifying loaded jar files.

Do you want me to open "debug" in server.properties and send you a more detailed log after trying again?

**Comment by notTamion** [comment]
No what i said earlier is correct. When i get home later today i will see if there is a way to avoid the error. I have already said this on a different issue before but i am not really maintaining this plugin anymore

**Comment by notTamion** [comment]
Question: is this for your testing environment or production

**Comment by OutHimic** [comment]
> Question: is this for your testing environment or production

Testing environment.
**My English level is a little poor, and I may not understand what you said correctly. Sorry.**
I have tested this pugin separately now.

[latest(Edited).log](https://github.com/user-attachments/files/16344078/latest.Edited.log)
This is all logs when I opened the "debug"
There are only one pugins : AutoServerUpdater-1.0.2.jar
Server ran on the Windows11 x64 Pro , **JDK22 (Is it because of this?)** , run in the directory "I:\TEST" , "I:\TEST\paper-1.21-107.jar"
The JDK file is located in "D:\JAVA\JDK22\bin\java.exe".
[server.properties.txt](https://github.com/user-attachments/files/16344155/server.properties.txt)

**Comment by OutHimic** [comment]
> Question: is this for your testing environment or production

Testing environment.
**My English level is a little poor, and I may not understand what you said correctly. Sorry.**
I have tested this pugin separately now.

[latest(Edited).log](https://github.com/user-attachments/files/16344078/latest.Edited.log)
This is all logs when I opened the "debug"
There are only one pugins : AutoServerUpdater-1.0.2.jar
Server ran on the Windows11 x64 Pro , **JDK22 (Is it because of this?)** , run in the directory "I:\TEST" , "I:\TEST\paper-1.21-107.jar"
The JDK file is located in "D:\JAVA\JDK22\bin\java.exe".
[server.properties.txt](https://github.com/user-attachments/files/16344155/server.properties.txt)

**Comment by notTamion** [comment]
Ok so. The issue is that java 21+ doesn't allow modifying jar files which are currently being used, which means that my plugin isn't able to overwrite that jar. Because i don't maintain this plugin anymore, i recommend you to use standalone software like my https://github.com/notTamion/MinecraftServerCLI when you want to do testing

EDIT: Also if you are having trouble translating try using ChatGPT or similar to translate text. It will often be able to translate stuff better than google translate

**Comment by OutHimic** [comment]
Okay , thanks .
